### ISSUE TITLE
Fatal Exception: java.lang.NoSuchFieldError No static field activity_result_invalid_parameters of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string' appears in base.apk!classes3.dex)

### ISSUE THREAD

**Issue by Ashok-Rupeek** [razorpay/razorpay-android-sample-app#318]
## Description
The below crash occur in v1.6.15
I found that this issue has been fixed in 1.6.10, but still this occur in above version. can you look into this issue
[refer here ](https://github.com/razorpay/razorpay-android-sample-app/issues/247)

```
Fatal Exception: java.lang.NoSuchFieldError: No static field activity_result_invalid_parameters of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string' appears in base.apk!classes3.dex)
       at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:174)
       at com.razorpay.b__J_.onCreate(b__J_.java:106)
       at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:26)
       at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
       at android.app.Activity.performCreate(Activity.java:8365)
       at android.app.Activity.performCreate(Activity.java:8343)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1379)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3912)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4096)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2441)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

```
## Razorpay SDK Version :
happens in `com.razorpay:checkout:1.6.15`

**Comment by vivekshindhe** [comment]
@Ashok-Rupeek can you please update to the latest version which is 1.6.22 and check with that?

**Comment by dhavalpatel666** [comment]
I am using 'com.razorpay:checkout:1.6.26' in my android dependencies.

While running the payment scenario for my app, I am getting the below error go to razorpay page

java.lang.NoSuchFieldError: No static field NO_OPTIONS of type Lcom/google/android/gms/common/api/Api$ApiOptions$NoOptions; in class Lcom/google/android/gms/common/api/Api$ApiOptions; or its superclasses (declaration of 'com.google.android.gms.common.api.Api$ApiOptions' appears in /data/app/com.smaple-suaPyGsU26tVlh7gKARYpQ==/base.apk!classes2.dex)
at com.google.android.gms.auth.api.phone.SmsRetrieverClient.(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
at com.google.android.gms.internal.auth-api-phone.zzab.(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
at com.google.android.gms.auth.api.phone.SmsRetriever.getClient(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:874)
at com.razorpay.J$0.secure(CheckoutBridge.java:27)
at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1370)
at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:55)
at com.razorpay.b$f.run(CheckoutPresenterImpl.java:1355)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6810)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by vivekshindhe** [comment]
@dhavalpatel666 This isn't reproducible at the moment for me. Is this happening in debug / release build? If the release build, have you added proguard rules there?

**Comment by AdarshRevankar** [comment]
Still facing this issue and issue is frequent, please provide support for this
```
Fatal Exception: java.lang.NoSuchFieldError: No static field activity_result_invalid_parameters of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string'
       at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:235)
       at com.razorpay.B$$W$.onCreate(BaseCheckoutActivity.java:112)
```

@vivekshindhe can you please check this ?

**Comment by vivekshindhe** [comment]
@AdarshRevankar This was fixed quite a while ago. Which version of the SDK are you using?

**Comment by AdarshRevankar** [comment]
Currently using 1.6.22 and observing issues there. For this issue I checked on the razorpay release notes for Android SDK, didn't find any specific comment. 

Could you please let me know the version this issue was fixed ?

**Comment by vivekshindhe** [comment]
@AdarshRevankar, Razorpay's release notes only go back to previous 5 version from the latest. Would suggest switching to the latest SDK. 1.6.41. This issue was resolved back then, but I don't remember the exact version.

**Comment by AdarshRevankar** [comment]
@vivekshindhe, facing same error even after upgrading the sdk to `1.6.41`. Are we missing any proguard rule here ? 

Please specify any missing rule other than [this](https://github.com/razorpay/razorpay-android-custom-sample-app/blob/master/proguard-project.txt)

**Comment by Nivas2129** [comment]
Hey, @yogeshelevn were you able to fix this issue? I am facing the same issue on a few android devices.

**Comment by ashishdvertex** [comment]
> This issue is fixed from our end. Please update the SDK (Gradle re-sync will update SDK automatically) and let us know if you see this issue in future. [@Ashok-Rupeek](https://github.com/Ashok-Rupeek) [@dhavalpatel666](https://github.com/dhavalpatel666) [@AdarshRevankar](https://github.com/AdarshRevankar) [@yogeshelevn](https://github.com/yogeshelevn) [@Nivas2129](https://github.com/Nivas2129)

java.lang.NoSuchMethodError: No static method logFunctionEntry(Ljava/lang/String;Ljava/lang/String;Z)V in class Lcom/razorpay/AnalyticsUtil; or its super classes (declaration of 'com.razorpay.AnalyticsUtil' appears in /data/app/~~ebn44rmH_28dXqJCWcf10g==/base.apk!classes20.dex)
                 	at com.razorpay.Checkout.preload(Checkout.java:316)

I am still facing this issue in production, current version is 1.6.41 and also tested in lower versions too but the application is crashing due to this issue.

**Comment by vivekshindhe** [comment]
@ashishdvertex We've made a release today that fixes this issue. Please wait for 15 mins until the maven repository gets refresh and re-run the steps mentioned above, i.e, run Sync project with gradle files.

**Comment by archie94** [comment]
@vivekshindhe is there any way to disable auto update of razorpay SDKs? Updating without explicit changelogs or an intimation are not something we would want to do. 
It leads to runtime crashes which can get missed in our qa cycle.

**Comment by sanket-algorizz** [comment]
The app was working normally until today, when this issue started occurring.

` ERROR  Your app just crashed. See the error below.
java.lang.NoSuchMethodError: No static method logFunctionEntry(Ljava/lang/String;Ljava/lang/String;Z)V in class Lcom/razorpay/AnalyticsUtil; or its super classes (declaration of 'com.razorpay.AnalyticsUtil' appears in /data/app/~~X5W5zuZDS7qYio0BJGuCBw==/com.myapp-jaF6t93kzNmM-WZ1d1Eszw==/base.apk!classes9.dex)
  com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:106)
  com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:25)
  com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
  android.app.Activity.performCreate(Activity.java:9216)
  android.app.Activity.performCreate(Activity.java:9194)
  android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1540)
  android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4358)
  android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4563)
  android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
  android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
  android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:2899)
  android.os.Handler.dispatchMessage(Handler.java:110)
  android.os.Looper.loopOnce(Looper.java:283)
  android.os.Looper.loop(Looper.java:392)
  android.app.ActivityThread.main(ActivityThread.java:9231)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:633)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026`

**Comment by sanket-algorizz** [comment]
Found a temp working solution.

Add this at the end in build.gradle

```
subprojects {
    configurations.all {
        resolutionStrategy {
            force "com.razorpay:checkout:1.6.38"
        }
    }
}
```

Add this in dependencies in app/build.gradle 

` implementation("com.razorpay:checkout:1.6.38")`

**Comment by ashishdvertex** [comment]
@vivekshindhe still no update found on Maven regarding this issue, Can you please share proper link or some resource where we can find the updated version of the SDK ?

**Comment by umeshsenquantic** [comment]
I’m still facing this issue. Is there any update, @vivekshindhe ?

`Fatal Exception: java.lang.NoSuchMethodError
No static method logFunctionEntry(Ljava/lang/String;Ljava/lang/String;Z)V in class Lcom/razorpay/AnalyticsUtil; or its super classes (declaration of 'com.razorpay.AnalyticsUtil' appears in /data/app/~~xejiMZJvJvPt4en9JxBn6g==/zone.dd-RzuzFQUE_Y9Yxx8qSOOQvw==/base.apk!classes3.dex)`
